#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff --cached --name-only | grep -qE '^\.env($|[^.])'; then
  echo "❌ ERROR: committing .env files is forbidden!"
  exit 1
fi

npx tsc --noEmit
# npm test
npx lint-staged