name: Prepare for Railway Deployment (with Submodules)

on:
  push:
    branches:
      - main # O la rama que Railway está escuchando para despliegues

jobs:
  prepare_repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permite que el GITHUB_TOKEN escriba en el repositorio
    steps:
      - name: Checkout Repository and Submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Asegúrate de que esta sea la versión de Node que usas

      - name: Install Dependencies
        run: npm install

      - name: Build NestJS Application
        run: npm run build

      - name: Remove .git and .gitmodules to avoid issues with Railway
        run: |
          rm -rf .git
          rm -f .gitmodules
          rm -rf src/domain/.git # Descomenta si es necesario, pero actions/checkout@v4 lo maneja bien

      - name: Push build artifacts to a dedicated deploy branch
        run: |
          git init # Inicializa un nuevo repo temporal
          # --- ¡AÑADE ESTAS DOS LÍNEAS AQUÍ! ---
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # ------------------------------------
          git add .
          git commit -m "Deployment artifacts for Railway"
          git branch -M railway-deploy # Renombra la rama localmente
          git remote add origin https://github.com/${{ github.repository }}.git
          git push --set-upstream origin railway-deploy --force